# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-U2ij3DgpYcep8krevvwHJQTIIiz7l8H
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

df=pd.read_csv("dataset/housing.csv")

df=pd.read_csv("dataset/holusing.csv")

df=pd.read_csv("dataset/holusing.csv")

/housing.csv

df=pd.read_csv("/housing.csv")

print(df)

printf(df.head(10))
print(df.tail(10))

print(df.head(10))
print(df.tail(10))

print(df.coloumns)
printf(df['total rooms'])

print(df.columns)
print(df['total_rooms'])

X = df['total_rooms'].head(150).values.reshape(-1,1)
y = df['median_house_value'].head(150).values.reshape(-1, 1)

plt.scatter(X, y)

plt.xlabel("Total Rooms")

plt.ylabel("Median House Value")
plt.title("Scatter Plot of Total Rooms vs. Median House Value")
plt.show()
print(df.describe())